global using Basket;
global using Catalog;
global using Ordering.Orders;
global using Carter;
global using Shared.Extensions;
global using Shared.Exceptions.Handler;
global using FluentValidation;
global using Serilog;
global using Shared.Behaviors;
