global using Shared.DDD;
global using Basket.Basket.Models;
global using Microsoft.EntityFrameworkCore;
global using System.Reflection;
global using Basket.Data;
global using Basket.Basket.Dtos;
global using FluentValidation;
global using Shared.Contracts.CQRS;
global using Basket.Basket.Exceptions;
global using Carter;
global using Microsoft.AspNetCore.Routing;
global using Microsoft.AspNetCore.Builder;
global using MediatR;
global using Mapster;
global using Microsoft.AspNetCore.Http;
global using Microsoft.AspNetCore.Mvc;
global using Basket.Data.Repository;
global using Shared.Messaing.Extensions;

